apps/product_app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),
    path('checker/', views.checker, name='checker'),
    path('get/', views.get, name='get'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

imperium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from two_factor.urls import urlpatterns as tf_urls

from . import views

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='adminpage'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', views.index, name='login'),
    path('send_email', views.send_email, name='send_email'),
    path('dashboard/', include('apps.dashboard_app.urls')),
    path('member/', include('apps.user_app.urls')),
    path('partner/', include('apps.partner_app.urls')),
    path('transaction/', include('apps.transaction_app.urls')),
    path('social-trading/', include('apps.social_trading_app.urls')),
    path('notice/', include('apps.notice_app.urls')),
    path('trading/', include('apps.trading_account_app.urls')),
    path('product/', include('apps.product_app.urls')),
    path('', include(tf_urls)),
)

apps/product_app/models.py
from django.db import models

# Create your models here.
class ProductTrading(models.Model):
    name = models.CharField(max_length=20)
    leverage = models.IntegerField(default=0)
    min_deposit = models.IntegerField(default=0)
    is_enable = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name)

apps/product_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.http import HttpResponse
from .models import ProductTrading
from django.views.decorators.http import require_http_methods
import json

from django_htmx.middleware import HtmxDetails

class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails

# Create your views here.
@require_http_methods(["GET"])
@login_required
def index(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, 'product_app/index.html')

def get(request: HtmxHttpRequest) -> HttpResponse:
    product = ProductTrading.objects.all().order_by('id')
    context = {
        'products': product,
    }
    return render(request, 'product_app/index-get.html', context)

@require_http_methods(["POST"])
def checker(request: HtmxHttpRequest) -> HttpResponse:
    if request.method == 'POST':
        post_data = request.POST
        product = get_object_or_404(ProductTrading, id=post_data['product_id'])
        
        # Menginisialisasi pesan
        showMessage = showMessage = f"{product.name} product has been saved."

        if 'group' in post_data:
            group = post_data['group']
            if group != product.name:
                product.name = group
                showMessage = f"{product.name} product name change has been successfully saved."

        if 'leverage' in post_data:
            leverage = post_data['leverage']
            if leverage != product.leverage:
                product.leverage = leverage
                
        if 'min_deposit' in post_data:
            min_deposit = post_data['min_deposit']
            if min_deposit != product.min_deposit:
                product.min_deposit = min_deposit

        if 'enables' in post_data:
            enables = post_data['enables'].lower() == 'true'
            if enables != product.is_enable:
                product.is_enable = enables
                showMessage = f"{product.name} product enable has been {'enabled' if enables else 'disabled'}."

        product.save()

        return HttpResponse(status=204,
                            headers={'HX-Trigger': json.dumps({
                                'productChange': None,
                                'showMessage': showMessage
                            })}
        )
@require_http_methods(["POST"])
def add(request: HtmxHttpRequest) -> HttpResponse:
    product = ProductTrading.objects.all().order_by('id')
    post_data = []
    if request.method == 'POST':
        post_data = request.POST
        nama = post_data['group']
        ProductTrading.objects.create(
            name=nama,
            leverage=int(post_data['leverage']),
            min_deposit=int(post_data['min-deposit']),
        )
        
    context = {
        'products': product
    }

    return HttpResponse(status=204,
                            headers={'HX-Trigger': json.dumps({
                                    'productChange':None,
                                    'showMessage':f'Product {nama} has been added'
                                }
        )})
@require_http_methods(["POST"])
def delete(request: HtmxHttpRequest) -> HttpResponse:

    if request.method == 'POST':
        product = get_object_or_404(ProductTrading, id=request.POST['product_id'])
        product.delete()

    return HttpResponse(status=204,
                            headers={'HX-Trigger': json.dumps({
                                    'productChange':None,
                                    'showMessage':f'Product {product.name} delete successfully.'
                                }
        )})

templates/product_app/index-add.html
{% for product in products %}
<div class="m-5">
  <div class="w-[384px] h-[434px] p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-5"
          hx-post="{% url "product:checker" %}"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
          hx-target="#resultdx"
          hx-swap="afterbegin"
          x-data="{enable:{{ product.is_enable|yesno:"true,false" }}}">

      <input type="text" name="product_id" id="product_id" value="{{product.id}}" hidden/>
      <div class="flex items-center gap-4 justify-between">
        <h5 class="text-xl font-medium text-gray-900 dark:text-white">{{product.name}}</h5>
        <input type="text" name="enables" id="enables" :value="enable" hidden/>
        <button @click="enable = !enable" :class="enable ? 'bg-green-700 hover:bg-green-800 dark:bg-green-700 dark:hover:bg-green-800' : 'bg-zinc-500 hover:bg-zinc-600' " type="submit" class="w-fit text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-800">Enable</button>
      </div>
      <div>
        <label for="group" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Group</label>
        <input type="text" name="group" id="group" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="ECN" value="{{product.name}}" required />
      </div>
      <div>
        <label for="leverage" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Leverage</label>
        <input type="number" name="leverage" id="leverage" placeholder="1000" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" value={{product.leverage}} required />
      </div>
      <div>
        <label for="min-deposit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Minimal Deposit</label>
        <input type="number" name="min-deposit" id="min-deposit" placeholder="500" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" value={{product.min_deposit}} required />
      </div>
      <div class="flex gap-2">
        <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Update</button>
        <button hx-post="{% url "product:delete" %}" class="w-full text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">delete</button>
      </div>
    </form>
  </div>
</div>
{% endfor %}

templates/product_app/index-checker.html
<div
  x-data="{ isVisible: true }"
  x-show="isVisible"
  id="toast-default"
  class="flex items-center w-full max-w-xs p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
  role="alert"
  x-transition:enter="transition ease-out duration-300"
  x-transition:enter-start="opacity-0 transform translate-y-2"
  x-transition:enter-end="opacity-100 transform translate-y-0"
  x-transition:leave="transition ease-in duration-300"
  x-transition:leave-start="opacity-100 transform translate-y-0"
  x-transition:leave-end="opacity-0 transform translate-y-2"
>
  <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:bg-blue-800 dark:text-blue-200">
    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
    </svg>
    <span class="sr-only">Fire icon</span>
  </div>
  <div class="ms-3 text-sm font-normal">Product {{product.name}} saved successfully.</div>
  <button @click="isVisible = false" type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-default" aria-label="Close">
    <span class="sr-only">Close</span>
    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
    </svg>
  </button>
</div>

templates/product_app/index-get.html
{% for product in products %}
<div class="m-5">
  <div class="w-[384px] h-[434px] p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
    <form class="space-y-5"
          hx-post="{% url "product:checker" %}"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
          hx-target="#resultdx"
          hx-swap="afterbegin"
          x-data="{enable:{{ product.is_enable|yesno:"true,false" }}}">

      <input type="text" name="product_id" id="product_id" value="{{product.id}}" hidden/>
      <div class="flex items-center gap-4 justify-between">
        <h5 class="text-xl font-medium text-gray-900 dark:text-white">{{product.name}}</h5>
        <input type="text" name="enables" id="enables" :value="enable" hidden/>
        <button x-text="enable == true ? 'Enable' : 'Disable'" @click="enable = !enable" :class="enable ? 'bg-green-700 hover:bg-green-800 dark:bg-green-700 dark:hover:bg-green-800' : 'bg-zinc-500 hover:bg-zinc-600' " type="submit" class="w-fit text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-800">Enable</button>
      </div>
      <div>
        <label for="group" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Group</label>
        <input type="text" name="group" id="group" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="ECN" value="{{product.name}}" required />
      </div>
      <div>
        <label for="leverage" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Leverage</label>
        <input type="number" name="leverage" id="leverage" placeholder="1000" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" value={{product.leverage}} required />
      </div>
      <div>
        <label for="min-deposit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Minimal Deposit</label>
        <input type="number" name="min-deposit" id="min-deposit" placeholder="500" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" value={{product.min_deposit}} required />
      </div>
      <div class="flex gap-2">
        <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Update</button>
        <button hx-post="{% url "product:delete" %}" class="w-full text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">delete</button>
      </div>
    </form>
  </div>
</div>
{% endfor %}

templates/product_app/index.html
{% extends "base.html" %}{% load django_htmx %}{% load static %}{% load static tailwind_tags %}

<!-- css -->
{% block css %}{% endblock css %}

<!-- js_head -->
{% block js_head %}
<script src="{% static "js/htmx.min.js" %}"></script>
<script src="//unpkg.com/alpinejs" defer></script>
<script src="{% static 'js/htmx.js' %}" defer></script>
<script src="{% static 'js/ext/debug.js' %}" defer></script>
<script src="{% static 'js/ext/event-header.js' %}" defer></script>
{% endblock js_head %}

<!-- content -->
{% block content %}
<div class="overflow-x-auto flex" x-data="{ boxes: [] }" >
  <div class="flex"
       id="resultxd"
       hx-target="this" 
       hx-swap="innerHTML"
       hx-get="{% url 'product:get' %}"
       hx-trigger="load, productChange from:body">

    <p>Loading...</p>
  </div>

  <div class="m-5">
    <div class="w-[384px] h-[434px] p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
      <form class="space-y-5"
            hx-post="{% url "product:add" %}"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            hx-target="#resultxd"
            x-data="{enable:{{ product.is_enable|yesno:"true,false" }}}">
        <div class="flex items-center gap-4 justify-between">
          <h5 class="text-xl font-medium text-gray-900 dark:text-white">Add Product</h5>
          <input type="text" name="enables" id="enables" :value="enable" hidden/>
          <button @click="enable = !enable" :class="enable ? 'bg-green-700 hover:bg-green-800 dark:bg-green-700 dark:hover:bg-green-800' : 'bg-zinc-500 hover:bg-zinc-600' " type="submit" class="w-fit text-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:focus:ring-blue-800">Enable</button>
        </div>
        <div>
          <label for="group" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Group</label>
          <input type="text" name="group" id="group" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="ECN" value="{{product.name}}" required />
        </div>
        <div>
          <label for="leverage" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Leverage</label>
          <input type="number" name="leverage" id="leverage" placeholder="1000" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" value={{product.leverage}} required />
        </div>
        <div>
          <label for="min-deposit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Minimal Deposit</label>
          <input type="number" name="min-deposit" id="min-deposit" placeholder="500" autocomplete="off" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" value={{product.min_deposit}} required />
        </div>
        <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add</button>
      </form>
    </div>
  </div>
</div>

<div id="resultdx" class="absolute z-50 right-10 top-[5%] hidden space-y-2 h-[65%] md:hidden md:flex-col justify-end">
  {% include "product_app/toast.html" %}
</div>


{% endblock content %}

<!-- javascript -->
{% block javascripts %}
{% django_htmx_script %}
<script>
  const toastContainer = document.querySelector("#resultdx");
  const toast = toastContainer.querySelector("#toast-body");

  function showToast(message) {
      toast.innerText = message;
      toastContainer.classList.remove('md:hidden');
      toastContainer.classList.add('md:flex');
      
      setTimeout(() => {
          toastContainer.classList.remove('md:flex');
          toastContainer.classList.add('md:hidden');
      }, 3000);
  }

  htmx.on('showMessage', (e) => {
      showToast(e.detail.value);
  });
</script>


{% endblock javascripts %}

templates/product_app/toast.html
<div
  x-data="{ isVisible: true }"
  x-show="isVisible"
  id="toast-default"
  class="flex items-center w-full max-w-xs p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
  role="alert"
  x-transition:enter="transition ease-out duration-300"
  x-transition:enter-start="opacity-0 transform translate-y-2"
  x-transition:enter-end="opacity-100 transform translate-y-0"
  x-transition:leave="transition ease-in duration-300"
  x-transition:leave-start="opacity-100 transform translate-y-0"
  x-transition:leave-end="opacity-0 transform translate-y-2"
>
  <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:bg-blue-800 dark:text-blue-200">
    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
    </svg>
    <span class="sr-only">Fire icon</span>
  </div>
  <div id="toast-body" class="ms-3 text-sm font-normal">Product {{product.name}} saved successfully.</div>
  <button @click="isVisible = false" type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-default" aria-label="Close">
    <span class="sr-only">Close</span>
    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
    </svg>
  </button>
</div>