apps/transaction_app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'transaction'

urlpatterns = [
    path('', views.index, name='index'),
    path('get/', views.deposit_get, name='deposit_get'),
    path('get-history/', views.deposit_history_get, name='deposit_history_get'),
    path('update/', views.deposit_update, name='deposit_update'),
    path('delete/', views.deposit_delete, name='deposit_delete'),
    path('withdrawal/', views.withdrawal, name='withdrawal'),
    path('withdrawal/get/', views.withdrawal_get, name='withdrawal_get'),
    path('withdrawal/get-history/', views.withdrawal_history_get, name='withdrawal_history_get'),
    path('withdrawal/update/', views.withdrawal_update, name='withdrawal_update'),
    path('withdrawal/delete/', views.withdrawal_delete, name='withdrawal_delete'),
    path('internal_trans/', views.internal_trans, name='internal_trans'),
    path('internal_trans/get/', views.internal_trans_get, name='internal_trans_get'),
    path('internal_trans/get-history/', views.internal_trans_history_get, name='internal_trans_history_get'),
    path('internal_trans/update/', views.internal_trans_update, name='internal_trans_update'),
    path('internal_trans/delete/', views.internal_trans_delete, name='internal_trans_delete'),
]

imperium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from two_factor.urls import urlpatterns as tf_urls

from . import views

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='adminpage'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', views.index, name='login'),
    path('send_email', views.send_email, name='send_email'),
    path('dashboard/', include('apps.dashboard_app.urls')),
    path('member/', include('apps.user_app.urls')),
    path('partner/', include('apps.partner_app.urls')),
    path('transaction/', include('apps.transaction_app.urls')),
    path('social-trading/', include('apps.social_trading_app.urls')),
    path('notice/', include('apps.notice_app.urls')),
    path('trading/', include('apps.trading_account_app.urls')),
    path('product/', include('apps.product_app.urls')),
    path('', include(tf_urls)),
)

apps/transaction_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from apps.trading_account_app.models import TradingAccount

# Create your models here.
class Deposit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, default=5)
    bank_method = models.CharField(max_length=10)
    is_confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return str(self.user)
    
class DepositHistory(models.Model):

    CHOICES = [
        ('Rejected', 'Rejected'),
        ('Accepted', 'Accepted'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, default=5)
    bank_method = models.CharField(max_length=10)
    status = models.CharField(max_length=10, choices=CHOICES)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return str(self.user)
    
class Withdraw(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, default=5)
    bank_method = models.CharField(max_length=10)
    is_confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return str(self.user)
    
class WithdrawHistory(models.Model):

    CHOICES = [
        ('Rejected', 'Rejected'),
        ('Accepted', 'Accepted'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, default=5)
    bank_method = models.CharField(max_length=10)
    status = models.CharField(max_length=10, choices=CHOICES)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return str(self.user)
    
class IntTrans(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    from_account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, related_name='transfers_from_inttrans', default=1)
    to_account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, related_name='transfers_to_inttrans', default=1)
    is_confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return f"Transfer from {self.from_account} to {self.to_account} by {self.user}"

class IntTransHistory(models.Model):
    CHOICES = [
        ('Rejected', 'Rejected'),
        ('Accepted', 'Accepted'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    from_account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, related_name='transfers_from_history', default=1)
    to_account = models.ForeignKey(TradingAccount, on_delete=models.CASCADE, related_name='transfers_to_history', default=1)
    status = models.CharField(max_length=10, choices=CHOICES)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return str(self.user)

apps/transaction_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Deposit, Withdraw, IntTrans, DepositHistory, WithdrawHistory, IntTransHistory
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpRequest, HttpResponse, HttpResponseBadRequest
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from fast_pagination.helpers import FastPaginator
import json

from django_htmx.middleware import HtmxDetails

class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails

# Create your views here.
@login_required
def index(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, 'transaction_app/index.html')

@login_required
@require_http_methods(["GET"])
def deposit_get(request: HtmxHttpRequest) -> HttpResponse:

    if request.method == "GET":
        page_req = request.GET.get('req')
        if page_req == "ib":
            search_query = request.GET.get('simple-search', '')
            xreq = page_req
            mib_accounts = Deposit.objects.select_related('user').filter(is_confirm=False).order_by('id')

            if search_query:
                mib_accounts = mib_accounts.filter(
                    Q(user__username__icontains=search_query) |
                    Q(user__email__icontains=search_query) |
                    Q(user__first_name__icontains=search_query) |
                    Q(user__last_name__icontains=search_query) |
                    Q(created_at__icontains=search_query)
                )

            per_page = 5 if request.GET.get('record') == None else request.GET.get('record')
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        context = {
            'xreq': xreq,
            'mib': mib_page,
            'page_req': page_req,
        }

    return render(request, 'transaction_app/deposit-get.html', context)

@login_required
@require_http_methods(["GET"])
def deposit_history_get(request: HtmxHttpRequest) -> HttpResponse:

    if request.method == "GET":
        page_req = request.GET.get('req')
        if page_req == "ib":
            search_query = request.GET.get('simple-search', '')
            xreq = page_req
            mib_accounts = DepositHistory.objects.select_related('user').all().order_by('id')

            if search_query:
                mib_accounts = mib_accounts.filter(
                    Q(user__username__icontains=search_query) |
                    Q(user__email__icontains=search_query) |
                    Q(user__first_name__icontains=search_query) |
                    Q(user__last_name__icontains=search_query) |
                    Q(created_at__icontains=search_query)
                )

            per_page = 5 if request.GET.get('record') == None else request.GET.get('record')
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        context = {
            'xreq': xreq,
            'mib': mib_page,
            'page_req': page_req,
        }

    return render(request, 'transaction_app/deposit-history-get.html', context)

@require_http_methods(["POST"])
def deposit_update(request: HtmxHttpRequest) -> JsonResponse:
    if request.method == 'POST':
        group_id = request.POST.get('group')
        page_req = request.POST.get('req')
        if not group_id:
            return HttpResponseBadRequest("Group ID is required.")

        if page_req == "ib":
            
            mib_account = get_object_or_404(Deposit, id=group_id)
            mib_account.is_confirm = not mib_account.is_confirm
            mib_account.save()

            DepositHistory.objects.create(
                user=mib_account.user,
                amount=mib_account.amount,
                account=mib_account.account,
                bank_method=mib_account.bank_method,
                status='Accepted',
                created_at=mib_account.created_at,
            )

    cache.delete('index_page_cache_key')
    showMessage = "Product has been saved."
    response_data = {
        'productChange': None,
        'showMessage': showMessage
    }
    return JsonResponse(response_data, status=204, headers={'HX-Trigger': json.dumps(response_data)})

@require_http_methods(["POST"])
def deposit_delete(request: HtmxHttpRequest) -> JsonResponse:
    if request.method == 'POST':
        group_id = request.POST.get('group')
        page_req = request.POST.get('req')
        if not group_id:
            return HttpResponseBadRequest("Group ID is required.")

        if page_req == "ib":
            
            mib_account = get_object_or_404(Deposit, id=group_id)
            mib_account.delete()

            DepositHistory.objects.create(
                user=mib_account.user,
                amount=mib_account.amount,
                account=mib_account.account,
                bank_method=mib_account.bank_method,
                status='Rejected',
                created_at=mib_account.created_at,
            )

    cache.delete('index_page_cache_key')
    showMessage = "Product has been saved."
    response_data = {
        'productChange': None,
        'showMessage': showMessage
    }
    return JsonResponse(response_data, status=204, headers={'HX-Trigger': json.dumps(response_data)})

@login_required
def withdrawal(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, 'transaction_app/withdrawal.html')

@login_required
@require_http_methods(["GET"])
def withdrawal_get(request: HtmxHttpRequest) -> HttpResponse:

    if request.method == "GET":
        page_req = request.GET.get('req')
        if page_req == "ib":
            search_query = request.GET.get('simple-search', '')
            xreq = page_req
            mib_accounts = Withdraw.objects.select_related('user').filter(is_confirm=False).order_by('id')

            if search_query:
                mib_accounts = mib_accounts.filter(
                    Q(user__username__icontains=search_query) |
                    Q(user__email__icontains=search_query) |
                    Q(user__first_name__icontains=search_query) |
                    Q(user__last_name__icontains=search_query) |
                    Q(created_at__icontains=search_query)
                )

            per_page = 5 if request.GET.get('record') == None else request.GET.get('record')
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        context = {
            'xreq': xreq,
            'mib': mib_page,
            'page_req': page_req,
        }

    return render(request, 'transaction_app/withdrawal-get.html', context)

@login_required
@require_http_methods(["GET"])
def withdrawal_history_get(request: HtmxHttpRequest) -> HttpResponse:

    if request.method == "GET":
        page_req = request.GET.get('req')
        if page_req == "ib":
            search_query = request.GET.get('simple-search', '')
            xreq = page_req
            mib_accounts = WithdrawHistory.objects.select_related('user').all().order_by('id')

            if search_query:
                mib_accounts = mib_accounts.filter(
                    Q(user__username__icontains=search_query) |
                    Q(user__email__icontains=search_query) |
                    Q(user__first_name__icontains=search_query) |
                    Q(user__last_name__icontains=search_query) |
                    Q(created_at__icontains=search_query)
                )

            per_page = 5 if request.GET.get('record') == None else request.GET.get('record')
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        context = {
            'xreq': xreq,
            'mib': mib_page,
            'page_req': page_req,
        }

    return render(request, 'transaction_app/deposit-history-get.html', context)

@require_http_methods(["POST"])
def withdrawal_update(request: HtmxHttpRequest) -> JsonResponse:
    if request.method == 'POST':
        group_id = request.POST.get('group')
        page_req = request.POST.get('req')
        if not group_id:
            return HttpResponseBadRequest("Group ID is required.")

        if page_req == "ib":
            
            mib_account = get_object_or_404(Withdraw, id=group_id)
            mib_account.is_confirm = not mib_account.is_confirm
            mib_account.save()

            WithdrawHistory.objects.create(
                user=mib_account.user,
                amount=mib_account.amount,
                account=mib_account.account,
                bank_method=mib_account.bank_method,
                status='Accepted',
                created_at=mib_account.created_at,

templates/transaction_app/withdrawal.html
{% extends "base.html" %}{% load django_htmx %}{% load static %} {% load static tailwind_tags %}

<!-- css -->
{% block css %}{% endblock css %}

<!-- js_head -->
{% block js_head %}
<script src="{% static "js/htmx.min.js" %}"></script>
<script src="//unpkg.com/alpinejs" defer></script>
<script src="{% static 'js/htmx.js' %}" defer></script>
<script src="{% static 'js/ext/debug.js' %}" defer></script>
<script src="{% static 'js/ext/event-header.js' %}" defer></script>
{% endblock js_head %}

<!-- content -->
{% block content %}
<div
  class="p-4 my-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
  <!-- Card header -->
  <div class="items-center justify-between lg:flex">
    <div class="mb-4 lg:mb-0">
      <h3 class="mb-2 text-xl font-bold text-gray-900 dark:text-white">
        List All Withdrawal Request
      </h3>
      <span class="text-base font-normal text-gray-500 dark:text-gray-400">
        This is a list of withdrawal request
      </span>
    </div>
    <div class="items-center sm:flex">
      <form class="max-w-sm mx-auto flex items-center justify-center space-x-3" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <label for="record" class="block text-sm font-medium text-gray-900 dark:text-white">Show</label>
        <select hx-get="{% url "transaction:deposit_get" %}?req=ib" hx-target="#resultmib" id="record" name="record" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
          <option value="" selected>Select</option>
          <option value="10">10</option>
          <option value="50">50</option>
          <option value="100">100</option>
          <option value="1000">1000</option>
        </select>
      </form>
      <form class="flex items-center mx-4" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <label for="simple-search" class="sr-only">Search</label>
        <div class="relative w-full">
          <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
          </div>
          <input type="text" id="simple-search" name="simple-search" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search" required hx-get="{% url "transaction:deposit_get" %}?req=ib" hx-trigger="keyup changed delay:300ms" hx-target="#resultmib">
        </div>
      </form>       
      <div class="flex items-center">
        <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
          Actions
          <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M19 9l-7 7-7-7"></path>
          </svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
          <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown">
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
            </li>
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">CSV</a>
            </li>
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
            </li>
          </ul>
          <div class="py-1">
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add New</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="resultmib" hx-target="this" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-swap="innerHTML" hx-get="{% url 'transaction:withdrawal_get' %}?req=ib" hx-trigger="load, productChange from:body">
    <svg aria-hidden="true" class="w-8 h-8 mt-5 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
      <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
    </svg>
  </div>
</div>

<div
  class="p-4 my-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
  <!-- Card header -->
  <div class="items-center justify-between lg:flex">
    <div class="mb-4 lg:mb-0">
      <h3 class="mb-2 text-xl font-bold text-gray-900 dark:text-white">
        List All Withdrawal History
      </h3>
      <span class="text-base font-normal text-gray-500 dark:text-gray-400">
        This is a list of withdrawal history
      </span>
    </div>
    <div class="items-center sm:flex">
      <form class="max-w-sm mx-auto flex items-center justify-center space-x-3" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <label for="record" class="block text-sm font-medium text-gray-900 dark:text-white">Show</label>
        <select hx-get="{% url "transaction:deposit_history_get" %}?req=ib" hx-target="#resultib" id="record" name="record" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
          <option value="" selected>Select</option>
          <option value="10">10</option>
          <option value="50">50</option>
          <option value="100">100</option>
          <option value="1000">1000</option>
        </select>
      </form>
      <form class="flex items-center mx-4" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        <label for="simple-search" class="sr-only">Search</label>
        <div class="relative w-full">
          <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
            </svg>
          </div>
          <input type="text" id="simple-search" name="simple-search" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search" required hx-get="{% url "transaction:deposit_history_get" %}?req=ib" hx-trigger="keyup changed delay:300ms" hx-target="#resultib">
        </div>
      </form>       
      <div class="flex items-center">
        <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
          Actions
          <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M19 9l-7 7-7-7"></path>
          </svg>
        </button>
        <!-- Dropdown menu -->
        <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
          <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown">
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
            </li>
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">CSV</a>
            </li>
            <li>
              <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
            </li>
          </ul>
          <div class="py-1">
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add New</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="resultib" hx-target="this" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-swap="innerHTML" hx-get="{% url 'transaction:withdrawal_history_get' %}?req=ib" hx-trigger="load, productChange from:body">
    <svg aria-hidden="true" class="w-8 h-8 mt-5 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
      <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
    </svg>
  </div>
</div>
{% endblock content %}

<!-- javascript -->
{% block javascripts %}
{% django_htmx_script %}
{% endblock javascripts %}