apps/user_app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('verification/', views.verification, name='verification'),
    path('api/get-users/', views.get_users, name='get_users'),
    path('api/get-verification/', views.get_verification, name='get_users_verify')
]

imperium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from two_factor.urls import urlpatterns as tf_urls

from . import views

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='adminpage'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', views.index, name='login'),
    path('send_email', views.send_email, name='send_email'),
    path('dashboard/', include('apps.dashboard_app.urls')),
    path('member/', include('apps.user_app.urls')),
    path('partner/', include('apps.partner_app.urls')),
    path('transaction/', include('apps.transaction_app.urls')),
    path('social-trading/', include('apps.social_trading_app.urls')),
    path('notice/', include('apps.notice_app.urls')),
    path('trading/', include('apps.trading_account_app.urls')),
    path('product/', include('apps.product_app.urls')),
    path('', include(tf_urls)),
)

apps/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class PersonalDetail(models.Model):

    ID_CHOICES = [
        ('idcard', 'ID Card'),
        ('passport', 'Passport'),
    ]

    MARITAL_CHOICES = [
        ('married', 'Married'),
        ('widowed', 'Widowed'),
        ('separated', 'Separated'),
        ('divorced', 'Divorced'),
        ('single', 'Single'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = PhoneNumberField(blank=True)
    id_type = models.CharField(max_length=20, choices=ID_CHOICES)
    id_number = models.BigIntegerField()
    marital_status = models.CharField(max_length=20, choices=MARITAL_CHOICES)
    country = models.CharField(max_length=20)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    postal = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class BankDetail(models.Model):
    user = models.OneToOneField(PersonalDetail, on_delete=models.CASCADE)
    account_name = models.CharField(max_length=100)
    bank_account = models.BigIntegerField()
    bank_address = models.CharField(max_length=100)
    swift_code = models.BigIntegerField(blank=True, default=0)
    bank_name = models.CharField(max_length=100)


class Wallet(models.Model):
    user = models.OneToOneField(PersonalDetail, on_delete=models.CASCADE)
    wallet = models.BigIntegerField()

apps/user_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from .models import PersonalDetail,BankDetail, Wallet
from apps.trading_account_app.models import TradingAccount
from apps.partner_app.models import IbAccount, IbList
import json
from django.http import JsonResponse
from django.db.models import Prefetch
from django.core.serializers.json import DjangoJSONEncoder

def get_breadcrumb(path):
    parts = path.strip('/').split('/')
    breadcrumbs = [{'title': part.capitalize(), 'url': '/'.join(parts[:i+1])} for i, part in enumerate(parts)]
    return breadcrumbs


@login_required
def index(request):
    return render(request, 'user_app/index.html')

def get_users(request):
    start = int(request.POST.get('start', 0))
    length = int(request.POST.get('length', 100))
    filter_by = request.POST.get('filter_by', "")
    filter_value = request.POST.get('filter_value', "")

    total_records = User.objects.count()

    if length == 0:
        length = total_records

    users = User.objects.prefetch_related(
        Prefetch('personaldetail', queryset=PersonalDetail.objects.all()),
        Prefetch('personaldetail__bankdetail', queryset=BankDetail.objects.all()),
        Prefetch('personaldetail__wallet', queryset=Wallet.objects.all()),
        Prefetch('tradingaccount_set', queryset=TradingAccount.objects.all()),
        Prefetch('ib_lists', queryset=IbList.objects.all())  
    ).order_by('id')

    if filter_by and filter_value:
        
        users = users.filter(**{filter_by: filter_value})

    filtered_users = users[start:start + length]  
    filtered_records = len(filtered_users)  

    if length != total_records:
        filtered_records = min(filtered_records, length)

    users = users[start:start + length]

    data = []
    for user in users:
        user_data = {
            'id': user.id,
            'username': user.username,
            'last_login': user.last_login,
            'is_superuser': user.is_superuser,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'is_staff': user.is_staff,
            'is_active': user.is_active,
            'date_joined': user.date_joined,
            'trading_accounts': [],
            'ib_lists': []  
        }

        
        for account in user.tradingaccount_set.all():
            trading_account_data = {
                'account_number': account.account_number,
                'account_deposit': account.account_deposit,
                'dm_group': account.dm_group.id,  
                'created_at': account.created_at,
                'last_updated': account.last_updated
            }
            user_data['trading_accounts'].append(trading_account_data)

        
        try:
            ib_list = user.ib_lists
            if ib_list:  
                ib_list_data = {
                    'ib': ib_list.ib.name
                }
                user_data['ib_lists'] = [ib_list_data]
            else:
                user_data['ib_lists'] = None
        except IbList.DoesNotExist:
            user_data['ib_lists'] = None

        try:
            personal_detail = user.personaldetail
            user_data['personalDetail'] = {
                'phone': str(personal_detail.phone),
                'id_number': personal_detail.id_number,
                'marital_status': personal_detail.marital_status,
                'country': personal_detail.country,
                'state': personal_detail.state,
                'city': personal_detail.city,
                'postal': personal_detail.postal,
                'address': personal_detail.address,
                'last_updated': personal_detail.last_updated,
            }

            bank_detail = personal_detail.bankdetail
            user_data['bankDetail'] = {
                'account_name': bank_detail.account_name,
                'bank_account': bank_detail.bank_account,
                'bank_address': bank_detail.bank_address,
                'swift_code': bank_detail.swift_code,
                'bank_name': bank_detail.bank_name,
            }
        except PersonalDetail.DoesNotExist:
            user_data['personalDetail'] = None
            user_data['bankDetail'] = None

        data.append(user_data)


    if not filter_by or not filter_value:
       filtered_records = total_records

    response = {
        'recordsTotal': total_records,
        'recordsFiltered': filtered_records,
        'data': data
    }

    return JsonResponse(response, safe=False, encoder=DjangoJSONEncoder)


@login_required
def verification(request):
    return render(request, 'user_app/verification.html')

def get_verification(request):
    start = int(request.GET.get('start', 0))
    length = int(request.GET.get('length', 0))
    filter_by = request.GET.get('filter_by', '')
    filter_value = request.GET.get('filter_value', '')

    total_records = PersonalDetail.objects.count()

    if length == 0:
        length = total_records

    verification = PersonalDetail.objects.select_related('user').all()

    if filter_by and filter_value:
        
        verification = verification.filter(**{filter_by: filter_value})

    filtered_verify = verification[start:start + length]  
    filtered_records = len(filtered_verify)  

    if length != total_records:
        filtered_records = min(filtered_records, length)

    verification = verification[start:start + length]

    data = []
    for verify in verification:
        verify_data = {
            'last_updated': verify.last_updated,
            'first_name': verify.first_name,
            'last_name': verify.last_name,
            'username': verify.user.username,
            'email': verify.email,
            'phone': str(verify.phone),
            'city': verify.city
        } 

        data.append(verify_data)

    if not filter_by or not filter_value:
       filtered_records = total_records

    response = {
        'recordsTotal': total_records,
        'recordsFiltered': filtered_records,
        'data': data
    }

    return JsonResponse(response, safe=False, encoder=DjangoJSONEncoder)

templates/user_app/index.html
{% extends "base.html" %}{% load static %} {% load static tailwind_tags %}

<!-- css -->
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "css/vendor/datatable/dataTables.tailwindcss.css" %}">
{% endblock css %}

<!-- js_head -->
{% block js_head %}
<script src="{% static "js/vendor/datatable/jquery-3.7.1.js" %}"></script>
<script src="{% static "js/vendor/datatable/dataTables.js" %}"></script>
<script src="{% static "js/vendor/datatable/dataTables.tailwindcss.js" %}"></script>
<script src="https://cdn.tailwindcss.com/"></script>
{% endblock js_head %}

<!-- content -->
{% block content %}
<div class="pt-4 pr-4 pl-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:pt-6 sm:pr-6 sm:pl-6 sm:pb-2 dark:bg-gray-800">
  <!-- Card header -->
  <div class="items-center justify-between lg:flex">
    <div class="mb-4 lg:mb-0">
      <h3 class="mb-2 text-xl font-bold text-gray-900 dark:text-white">
        Account Member
      </h3>
      <span class="text-base font-normal text-gray-500 dark:text-gray-400">
        This is a list of account member
      </span>
    </div>
    <div class="items-center sm:flex">
        <div class="flex items-center mr-1">
            <div class="relative w-full">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">                    
                    <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M18.8 4H5.2a1 1 0 0 0-.7 1.7l5.3 6 .2.7v4.8c0 .2 0 .4.2.4l3 2.3c.3.2.8 0 .8-.4v-7.1c0-.3 0-.5.2-.7l5.3-6a1 1 0 0 0-.7-1.7Z"/>
                    </svg>
                </div>
                <select id="filter_by" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 pl-10 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                    <option value="">Search By</option>
                    <option value="email">Email</option>
                    <option value="first_name">Name</option>
                    <option value="last_name">Surname</option>
                    <option value="date_joined">Created</option>
                </select>
            </div>
        </div>       
        <div class="flex items-center mr-3">
            <div class="relative w-full">
                <div class="flex">
                    <input type="text" id="filter_value" class="rounded-none rounded-s-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-primary-500 focus:border-primary-500 block flex-1 min-w-0 w-full text-sm p-2  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search">
                    <span onclick="loadDataUsers()" style="cursor: pointer;" class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-e-0 border-gray-300 rounded-e-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                        </svg>
                    </span>                    
                </div>
            </div>
        </div>
        <div class="flex items-center">
          <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-blue-800 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
            Actions
            <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M19 9l-7 7-7-7"></path>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown">
              <li>
                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
              </li>
              <li>
                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">CSV</a>
              </li>
              <li>
                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
              </li>
            </ul>
            <div class="py-1">
              <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add New</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-col">    
        {% csrf_token %}            
        <table id="tableMembers" class="divide-gray-200 dark:divide-gray-600">
            <thead class="bg-gray-100 dark:bg-gray-700">
                <tr>
                    <th>Email</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>IB</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
{% endblock content %}

<!-- javascript -->
{% block javascripts %}
<script>
    $(document).ready(function() {
        loadDataUsers();
    });

    function loadDataUsers() {
        table = $('#tableMembers').DataTable({
            destroy: true,
            processing: true,
            serverSide: true,
            paging: true,
            pageLength: 10,
            order: [],
            ajax: {
                url: "{% url 'user:get_users' %}",
	            type: 'POST',
				dataType: "JSON",
                data: {                    
					filter_by: $("#filter_by").val(),
					filter_value: $("#filter_value").val(),
                    csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val()
                }
            },
            pagingType: "simple_numbers",
            searching: false,
            lengthChange: false,
            columns : [
                {
                    "data": "email",
                    "mRender": function(data, type, row) {
                        return `<a href="" class="text-blue-500 hover:underline">${row.email}</a>`;
                    }
                },
                {
                    "data": "first_name",
                },
                {
                    "data": "last_name",
                },
                {
                    "data": "date_joined",
                },
                {
                    "data": "username",
                    "mRender": function(data, type, row) {
                        var contentText = (row.personalDetail === null) ? "Not Verified" : "Verified";
                        return contentText;
                    }
                },
                {
                    "data": "ib_lists",
                    "mRender": function(data, type, row) {
                        if (row.ib_lists && row.ib_lists.length > 0) {
                            return row.ib_lists[0].ib;
                        } else {
                            return "-";
                        }
                    }
                }       
            ]
        });
    }
</script>
{% endblock javascripts %}

templates/user_app/verification.html
{% extends "base.html" %}{% load static %} {% load static tailwind_tags %}

<!-- css -->
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "css/vendor/datatable/dataTables.tailwindcss.css" %}">
{% endblock css %}

<!-- js_head -->
{% block js_head %}
<script src="{% static "js/vendor/datatable/jquery-3.7.1.js" %}"></script>
<script src="{% static "js/vendor/datatable/dataTables.js" %}"></script>
<script src="{% static "js/vendor/datatable/dataTables.tailwindcss.js" %}"></script>
<script src="https://cdn.tailwindcss.com/"></script>
{% endblock js_head %}

<!-- content -->
{% block content %}
<div class="pt-4 pr-4 pl-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:pt-6 sm:pr-6 sm:pl-6 sm:pb-2 dark:bg-gray-800">
  <!-- Card header -->
  <div class="items-center justify-between lg:flex">
    <div class="mb-4 lg:mb-0">
      <h3 class="mb-2 text-xl font-bold text-gray-900 dark:text-white">
        Account Member
      </h3>
      <span class="text-base font-normal text-gray-500 dark:text-gray-400">
        This is a list of account member
      </span>
    </div>
    <div class="items-center sm:flex">
        <div class="flex items-center mr-1">
            <div class="relative w-full">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">                    
                    <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M18.8 4H5.2a1 1 0 0 0-.7 1.7l5.3 6 .2.7v4.8c0 .2 0 .4.2.4l3 2.3c.3.2.8 0 .8-.4v-7.1c0-.3 0-.5.2-.7l5.3-6a1 1 0 0 0-.7-1.7Z"/>
                    </svg>
                </div>
                <select id="filter_by" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 pl-10 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                    <option value="">Search By</option>
                    <option value="email">Email</option>
                    <option value="first_name">Name</option>
                    <option value="last_name">Surname</option>
                    <option value="date_joined">Created</option>
                </select>
            </div>
        </div>       
        <div class="flex items-center mr-3">
            <div class="relative w-full">
                <div class="flex">
                    <input type="text" id="filter_value" class="rounded-none rounded-s-lg bg-gray-50 border border-gray-300 text-gray-900 focus:ring-primary-500 focus:border-primary-500 block flex-1 min-w-0 w-full text-sm p-2  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search">
                    <span onclick="loadDataUsers()" style="cursor: pointer;" class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border border-e-0 border-gray-300 rounded-e-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                        </svg>
                    </span>                    
                </div>
            </div>
        </div>
        <div class="flex items-center">
          <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white rounded-lg bg-blue-800 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
            Actions
            <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M19 9l-7 7-7-7"></path>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown">
              <li>
                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
              </li>
              <li>
                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">CSV</a>
              </li>
              <li>
                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Excel</a>
              </li>
            </ul>
            <div class="py-1">
              <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Add New</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-col">    
        {% csrf_token %}            
        <table id="tableMembers" class="divide-gray-200 dark:divide-gray-600">
            <thead class="bg-gray-100 dark:bg-gray-700">
              <tr>
                <th>Created</th>
                <th>Name</th>
                <th>Email</th>
                <th>Username</th>
                <th>Phone</th>
                <th>City</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
{% endblock content %}

<!-- javascript -->
{% block javascripts %}
<script>
    $(document).ready(function() {
        loadDataUsers();
    });

    function loadDataUsers() {
        table = $('#tableMembers').DataTable({
            destroy: true,
            processing: true,
            serverSide: true,
            paging: true,
            pageLength: 10,
            order: [],
            ajax: {
                url: "{% url 'user:get_users_verify' %}",
	            type: 'POST',
				dataType: "JSON",
                data: {                    
					filter_by: $("#filter_by").val(),
					filter_value: $("#filter_value").val(),
                    csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val()
                }
            },
            pagingType: "simple_numbers",
            searching: false,
            lengthChange: false,
            columns : [
            {
              "data": "last_updated"
            },
            {
              "data": "first_name",
              "mRender": function(data, type, row) {
                return row.first_name + ' ' + row.last_name;
              }
            },
            {
                "data": "email",
                "mRender": function(data, type, row) {
                    return `<a href="" class="text-blue-500 hover:underline">${row.email}</a>`;
                }
            },
            {
                "data": "username",
            },
            {
                "data": "phone",
            },
            {
                "data": "city"
            }          
        ]
        });
    }
</script>
{% endblock javascripts %}