apps/partner_app/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'partner'

urlpatterns = [
    path('', views.index, name='index'),
    path('get/', views.partner_get, name='partner_get'),
    path('update/', views.partner_update, name='partner_update'),
    path('wallet/', views.wallet, name='wallet'),
    path('history/get/', views.history_get, name='history_get'),
    path('verification/', views.verification, name='verification'),
    path('verification/get/', views.verify_get, name='verify_get'),
    path('verification/update/', views.verify_update, name='verify_update'),
    path('verification/delete/', views.verify_delete, name='verify_delete'),
    path('request/', views.request, name='request'),
]

imperium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from two_factor.urls import urlpatterns as tf_urls

from . import views

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='adminpage'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', views.index, name='login'),
    path('send_email', views.send_email, name='send_email'),
    path('dashboard/', include('apps.dashboard_app.urls')),
    path('member/', include('apps.user_app.urls')),
    path('partner/', include('apps.partner_app.urls')),
    path('transaction/', include('apps.transaction_app.urls')),
    path('social-trading/', include('apps.social_trading_app.urls')),
    path('notice/', include('apps.notice_app.urls')),
    path('trading/', include('apps.trading_account_app.urls')),
    path('product/', include('apps.product_app.urls')),
    path('', include(tf_urls)),
)

apps/partner_app/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.trading_account_app.models import TradingAccount
from django.core.exceptions import ValidationError
from django.utils import timezone

class MibAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_confirm = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    active = models.BooleanField(default=True)
    def __str__(self):
        return str(self.user)
    

class IbAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="")
    account_number = models.OneToOneField(TradingAccount,on_delete=models.CASCADE)
    is_confirm = models.BooleanField(default=False)
    is_ib = models.BooleanField(default=False)
    is_sub_ib = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        if IbList.objects.filter(client_account=self.user).exists():
            self.is_ib = False
            self.is_sub_ib = True
        else:
            self.is_ib = True
            self.is_sub_ib = False

        super().save(*args, **kwargs)

class MibList(models.Model):
    mib = models.ForeignKey(MibAccount, on_delete=models.CASCADE)
    ib_account = models.OneToOneField(IbAccount, on_delete=models.CASCADE)

    # def clean(self):
    #     if IbAccount.objects.filter(user=self.client_account).exists():
    #         raise ValidationError('Client account is already an IB.')

    #     existing_ib_lists = IbList.objects.filter(client_account=self.client_account)
    #     if existing_ib_lists.exists():
    #         raise ValidationError('Client account already exists for another IB.')

    #     super().clean()

    def __str__(self):
        return str(self.mib)

class IbList(models.Model):
    ib = models.ForeignKey(IbAccount, on_delete=models.CASCADE)
    client_account = models.OneToOneField(User, on_delete=models.CASCADE, related_name='ib_lists')

    def clean(self):
        if IbAccount.objects.filter(user=self.client_account).exists():
            raise ValidationError('Client account is already an IB.')

        existing_ib_lists = IbList.objects.filter(client_account=self.client_account)
        if existing_ib_lists.exists():
            raise ValidationError('Client account already exists for another IB.')

        super().clean()

    def __str__(self):
        return str(self.ib)
    
class History(models.Model):
    CHOICES1 = [
        ('Rejected', 'Rejected'),
        ('Accepted', 'Accepted'),
    ]
    CHOICES2 = [
        ('IB', 'IB'),
        ('SUB IB', 'SUB IB'),
        ('MIB', 'MIB'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=CHOICES1)
    request = models.CharField(max_length=10, choices=CHOICES2)
    created_at = models.DateTimeField(default=timezone.now)

apps/partner_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import MibAccount, IbAccount, MibList, IbList, History
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpRequest, HttpResponse, HttpResponseBadRequest
from django.core.serializers.json import DjangoJSONEncoder
from django.views.decorators.http import require_http_methods
import json
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from fast_pagination.helpers import FastPaginator

from django_htmx.middleware import HtmxDetails

class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails

# Create your views here.
@login_required
# @cache_page(60*15, key_prefix='index_page_cache_key')
def index(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, 'partner_app/index.html')

# @cache_page(60*15)
@login_required
@require_http_methods(["GET"])
def partner_get(request: HtmxHttpRequest) -> HttpResponse:

    if request.method == "GET":
        page_req = request.GET.get('req')
        if page_req == "ib":
            search_query = request.GET.get('simple-search', '')
            xreq = page_req
            mib_accounts = IbAccount.objects.select_related('user').filter(Q(is_confirm=True)).order_by("id")

            if search_query:
                mib_accounts = mib_accounts.filter(
                    Q(user__username__icontains=search_query) |
                    Q(user__email__icontains=search_query) |
                    Q(user__first_name__icontains=search_query) |
                    Q(user__last_name__icontains=search_query) |
                    Q(created_at__icontains=search_query)
                )

            per_page = 5 if request.GET.get('record') == None else request.GET.get('record')
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        elif page_req == "mib":
            search_query = request.GET.get('simple-search', '')
            xreq = page_req
            mib_accounts = MibAccount.objects.select_related('user').filter(Q(is_confirm=True)).order_by('id')

            if search_query:
                mib_accounts = mib_accounts.filter(
                    Q(user__username__icontains=search_query) |
                    Q(user__email__icontains=search_query) |
                    Q(user__first_name__icontains=search_query) |
                    Q(user__last_name__icontains=search_query) |
                    Q(created_at__icontains=search_query)
                )

            per_page = 5 if request.GET.get('record') == None else request.GET.get('record')
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        context = {
            'xreq': xreq,
            'mib': mib_page,
            'page_req': page_req,
        }

    return render(request, 'partner_app/partner-get.html', context)

@require_http_methods(["POST"])
def partner_update(request: HtmxHttpRequest) -> JsonResponse:
    if request.method == 'POST':
        group_id = request.POST.get('group')
        page_req = request.POST.get('req')
        if not group_id:
            return HttpResponseBadRequest("Group ID is required.")
        
        if page_req == "ib":
            
            mib_account = get_object_or_404(IbAccount, id=group_id)
            mib_account.active = not mib_account.active
            mib_account.save()

        elif page_req == "mib":
            
            mib_account = get_object_or_404(MibAccount, id=group_id)
            mib_account.active = not mib_account.active
            mib_account.save()

    cache.delete('index_page_cache_key')
    showMessage = "Product has been saved."
    response_data = {
        'productChange': None,
        'showMessage': showMessage
    }
    return JsonResponse(response_data, status=204, headers={'HX-Trigger': json.dumps(response_data)})

@login_required
def wallet(request):
    return render(request, 'partner_app/wallet.html')

@login_required
# @cache_page(60*15, key_prefix='verify_cache_key')
def verification(request: HtmxHttpRequest) -> HttpResponse:
    return render(request, 'partner_app/verification.html')

@login_required
@require_http_methods(["GET"])
def history_get(request: HtmxHttpRequest) -> HttpResponse:
    search_query = request.GET.get('simple-search', '')
    mib_accounts = History.objects.select_related('user').all().order_by('id')

    if search_query:

        mib_accounts = mib_accounts.filter(
            Q(user__username__icontains=search_query) |
            Q(user__email__icontains=search_query) |
            Q(user__first_name__icontains=search_query) |
            Q(user__last_name__icontains=search_query) |
            Q(status__icontains=search_query) |
            Q(request__icontains=search_query) |
            Q(created_at__icontains=search_query)
        )

    per_page = 10 if request.GET.get('record') == None else request.GET.get('record')
    paginator = Paginator(mib_accounts, per_page)
    page_number = request.GET.get('page')

    try:
        mib_page = paginator.page(page_number)
    except PageNotAnInteger:
        mib_page = paginator.page(1)
    except EmptyPage:
        mib_page = paginator.page(paginator.num_pages)

    context = {
        'mib': mib_page,
    }
    return render(request, 'partner_app/history-get.html', context)

@login_required
@require_http_methods(["GET"])
def verify_get(request: HtmxHttpRequest) -> HttpResponse:
    if request.method == "GET":
        page_req = request.GET.get('req')
        if page_req == "ib":

            xreq = page_req
            mib_accounts = IbAccount.objects.select_related('user').filter(Q(is_confirm=False)).order_by('id')
            per_page = 3
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        elif page_req == "mib":
            
            xreq = page_req
            mib_accounts = MibAccount.objects.select_related('user').filter(Q(is_confirm=False))
            per_page = 3
            paginator = Paginator(mib_accounts, per_page)
            page_number = request.GET.get('page')
            try:
                mib_page = paginator.page(page_number)
            except PageNotAnInteger:
                mib_page = paginator.page(1)
            except EmptyPage:
                mib_page = paginator.page(paginator.num_pages)

        context = {
            'xreq': xreq,
            'mib': mib_page,
            'page_req': page_req,  # Mengirimkan parameter 'req' ke template
        }

    return render(request, 'partner_app/verification-get.html', context)

@require_http_methods(["POST"])
def verify_update(request: HtmxHttpRequest) -> JsonResponse:
    if request.method == 'POST':
        group_id = request.POST.get('group')
        page_req = request.POST.get('req')
        if not group_id:
            return HttpResponseBadRequest("Group ID is required.")
        
        if page_req == "ib":
            
            mib_account = get_object_or_404(IbAccount, id=group_id)
            mib_account.is_confirm = True
            mib_account.save()

            History.objects.create(
                user=mib_account.user,
                status="Accepted",
                request="IB"
            )

        elif page_req == "mib":
            
            mib_account = get_object_or_404(MibAccount, id=group_id)
            mib_account.is_confirm = True
            mib_account.save()

            History.objects.create(
                user=mib_account.user,
                status="Accepted",
                request="MIB"
            )

    cache.delete('verify_cache_key')
    showMessage = "Product has been saved."
    response_data = {
        'productChange': None,
        'showMessage': showMessage
    }
    return JsonResponse(response_data, status=204, headers={'HX-Trigger': json.dumps(response_data)})

@require_http_methods(["POST"])
def verify_delete(request: HtmxHttpRequest) -> JsonResponse:
    if request.method == 'POST':
        group_id = request.POST.get('group')
        page_req = request.POST.get('req')
        if not group_id:
            return HttpResponseBadRequest("Group ID is required.")
        
        if page_req == "ib":

            mib_account = get_object_or_404(IbAccount, id=group_id)
            mib_account.delete()
            History.objects.create(
                user=mib_account.user,
                status="Rejected",
                request="IB"
            )
        
        if page_req == "mib":

            mib_account = get_object_or_404(MibAccount, id=group_id)
            mib_account.delete()
            History.objects.create(
                user=mib_account.user,
                status="Rejected",
                request="MIB"
            )

    cache.delete('verify_cache_key')
    showMessage = "MibAccount has been deleted."
    response_data = {
        'productChange': None,
        'showMessage': showMessage
    }

templates/partner_app/verification-get.html
<!-- Table -->
<div class="flex flex-col mt-6">
  <div class="overflow-x-auto rounded-lg">
    <div class="inline-block min-w-full align-middle">
      <div class="overflow-hidden shadow sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-600">
          <thead class="bg-gray-100 dark:bg-gray-700">
            <tr>
              <th scope="col" class="p-4 text-xs font-bold tracking-wider text-left text-gray-500 uppercase dark:text-white">Date Reg</th>
              <th scope="col" class="p-4 text-xs font-bold tracking-wider text-left text-gray-500 uppercase dark:text-white">Name</th>
              <th scope="col" class="p-4 text-xs font-bold tracking-wider text-left text-gray-500 uppercase dark:text-white">Email</th>
              <th scope="col" class="p-4 text-xs font-bold tracking-wider text-left text-gray-500 uppercase dark:text-white">Username</th>
              <th scope="col" class="p-4 text-xs font-bold tracking-wider text-left text-gray-500 uppercase dark:text-white">Action</th>
            </tr>
          </thead>
          <tbody class="bg-white dark:bg-gray-800">
            {% for i in mib.object_list %}
            <tr class="even:bg-zinc-100">
            <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{i.created_at}}</td>
            <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{i.user.get_full_name}}</td>
            <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400"><a href="" class="text-blue-500 underline">{{i.user.email}}</a></td>
            <td class="p-3 text-sm font-normal text-gray-500 whitespace-nowrap dark:text-gray-400">{{i.user.username}}</td>
            <td class="p-3 space-x-2 whitespace-nowrap">
              <form hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-target="this" hx-swap="afterbegin">
                <input type="text" name="group" id="group" hidden value="{{i.id}}" required />
                <input type="text" name="req" id="req" hidden value="{{xreq}}" required />
                <button
                  type="submit"
                  id="changeActive"
                  hx-post="{% url "partner:verify_update" %}"
                  data-drawer-target="drawer-update-product-default"
                  data-drawer-show="drawer-update-product-default"
                  aria-controls="drawer-update-product-default"
                  data-drawer-placement="right"
                  class="inline-flex items-center px-3 py-2 text-xs font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
                  x-data="{loading:false}"
                  @click="loading=true">
                  <svg :class="loading ? 'hidden' : '' " class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path>
                    <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path>
                  </svg>
                  <svg :class="loading ? '' : 'hidden' " aria-hidden="true" class="w-4 h-4 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
                      <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
                  </svg>
                  <span x-text="loading ? 'Please Wait ...' : 'Accept {{xreq|upper}}'"></span>
                </button>
                <button
                  type="submit"
                  id="changeActive"
                  hx-post="{% url "partner:verify_delete" %}"
                  data-drawer-target="drawer-update-product-default"
                  data-drawer-show="drawer-update-product-default"
                  aria-controls="drawer-update-product-default"
                  data-drawer-placement="right"
                  class="inline-flex items-center px-3 py-2 text-xs font-medium text-center text-white rounded-lg bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800"
                  x-data="{loading:false}"
                  @click="loading=true">
                  <svg :class="loading ? 'hidden' : '' " class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path>
                    <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path>
                  </svg>
                  <svg :class="loading ? '' : 'hidden' " aria-hidden="true" class="w-4 h-4 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
                      <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
                  </svg>
                  <span x-text="loading ? 'Please Wait ...' : 'Reject'">Reject</span>
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- Card Footer -->
<div class="flex items-center justify-between pt-3 sm:pt-6">
  <div>
    <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
      Showing
      <span class="font-semibold text-gray-900 dark:text-white">{{ mib.number }}</span>
      of
      <span class="font-semibold text-gray-900 dark:text-white">{{ mib.paginator.num_pages }}</span>
    </span>
  </div>
  <div class="flex-shrink-0">
    <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0" aria-label="Table navigation">
      <ul class="inline-flex items-stretch -space-x-px">
        <li>
          {% if mib.has_previous %}
          <button hx-get="{% url "partner:verify_get" %}?req={{xreq}}&page={{ mib.previous_page_number }}" hx-target="#result{{xreq}}" class="flex items-center justify-center h-full py-1.5 px-3 ml-0 text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <span class="sr-only">Previous</span>
            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
            </svg>
          </button>
          {% else %}
          <div class="opacity-50 flex items-center justify-center h-full py-1.5 px-3 ml-0 text-gray-500 bg-white rounded-l-lg border border-gray-300 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400">
            <span class="sr-only">Previous</span>
            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
            </svg>
          </div>
          {% endif %}
        </li>
        {% for num in mib.paginator.page_range %}
        <li>
          {% if mib.number == num %}
          <div class="flex items-center justify-center text-sm z-10 py-2 px-3 leading-tight text-primary-600 bg-primary-50 border border-primary-300 hover:bg-primary-100 hover:text-primary-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{num}}</div>
          {% else %}
          <button hx-get="{% url "partner:verify_get" %}?req={{xreq}}&page={{num}}" hx-target="#result{{xreq}}" class="flex items-center justify-center text-sm py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{num}}</button>
          {% endif %}
        </li>
        {% endfor %}
        <li>
          {% if mib.has_next %}
          <button hx-get="{% url "partner:verify_get" %}?req={{xreq}}&page={{ mib.next_page_number }}" hx-target="#result{{xreq}}" class="flex items-center justify-center h-full py-1.5 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
            <span class="sr-only">Next</span>
            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
          </button>
          {% else %}
          <div class="opacity-50 flex items-center justify-center h-full py-1.5 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 ">
            <span class="sr-only">Next</span>
            <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
          </div>
          {% endif %}
        </li>
      </ul>
    </nav>
  </div>
</div>